[general]
working_directory = "None"
live_config_reload = true
ipc_socket = true

[window]
decorations = "Full"
blur = true
startup_mode = "Maximized"
padding = { x = 20, y = 20 }
opacity = 1

[cursor]
vi_mode_style = { shape = "Block", blinking = "Off" }

[scrolling]
history = 5000

[font]
size = 14

[keyboard]
bindings = [
{ key = "ArrowRight", mods = "Control", action = "IncreaseFontSize" },
{ key = "ArrowLeft", mods = "Control", action = "DecreaseFontSize" },
]

[colors.vi_mode_cursor]
cursor = '#ffc0cb'

[colors.primary]
background =  '#181818'
foreground =  '#b9b9b9'

# Normal colors
[colors.normal]
black   = '#3b3b3b'
red     = '#ed4a46'
green   = '#70b433'
yellow  = '#dbb32d'
blue    = '#368aeb'
magenta = '#eb6eb7'
cyan    = '#3fc5b7'
white   = '#b9b9b9'

# Bright colors
[colors.bright]
black   = '#777777'
red     = '#ff5e56'
green   = '#83c746'
yellow  = '#efc541'
blue    = '#4f9cfe'
magenta = '#ff81ca'
cyan    = '#56d8c9'
white   = '#dedede'
